import type { FoodOption } from "@/lib/types";

const createdAt = "2026-07-13T08:00:00.000Z";

export const sampleOptions: FoodOption[] = [
  {
    id: "sample-beef-rice",
    poolId: "solo-food",
    name: "番茄牛腩饭",
    kind: "delivery",
    priceLevel: 2,
    love: 5,
    health: 4,
    etaMinutes: 28,
    weatherTags: ["cold", "rain", "normal"],
    energyTags: ["low", "normal"],
    companionTags: ["solo", "friends"],
    active: true,
    craving: false,
    isSample: true,
    choiceCount: 0,
    preferenceDelta: 0,
    createdAt,
    updatedAt: createdAt,
  },
  {
    id: "sample-malatang",
    poolId: "solo-food",
    name: "楼下麻辣烫",
    kind: "restaurant",
    priceLevel: 1,
    love: 4,
    health: 3,
    etaMinutes: 18,
    weatherTags: ["hot", "cold", "rain", "normal"],
    energyTags: ["low", "normal"],
    companionTags: ["solo", "friends"],
    active: true,
    craving: false,
    isSample: true,
    choiceCount: 0,
    preferenceDelta: 0,
    createdAt,
    updatedAt: createdAt,
  },
  {
    id: "sample-fried-chicken",
    poolId: "solo-food",
    name: "炸鸡小食拼盘",
    kind: "delivery",
    priceLevel: 2,
    love: 4,
    health: 1,
    etaMinutes: 25,
    weatherTags: ["rain", "normal"],
    energyTags: ["low", "normal"],
    companionTags: ["solo", "friends"],
    active: true,
    craving: false,
    isSample: true,
    choiceCount: 0,
    preferenceDelta: 0,
    createdAt,
    updatedAt: createdAt,
  },
  {
    id: "sample-ramen",
    poolId: "solo-food",
    name: "日式豚骨拉面",
    kind: "restaurant",
    priceLevel: 2,
    love: 4,
    health: 3,
    etaMinutes: 35,
    weatherTags: ["cold", "rain"],
    energyTags: ["normal", "high"],
    companionTags: ["solo", "friends"],
    active: true,
    craving: false,
    isSample: true,
    choiceCount: 0,
    preferenceDelta: 0,
    createdAt,
    updatedAt: createdAt,
  },
  {
    id: "sample-rice-noodles",
    poolId: "solo-food",
    name: "清汤米线",
    kind: "food",
    priceLevel: 1,
    love: 4,
    health: 4,
    etaMinutes: 16,
    weatherTags: ["hot", "cold", "rain", "normal"],
    energyTags: ["low", "normal"],
    companionTags: ["solo"],
    active: true,
    craving: false,
    isSample: true,
    choiceCount: 0,
    preferenceDelta: 0,
    createdAt,
    updatedAt: createdAt,
  },
  {
    id: "sample-salad",
    poolId: "solo-food",
    name: "鸡胸轻食沙拉",
    kind: "delivery",
    priceLevel: 2,
    love: 3,
    health: 5,
    etaMinutes: 22,
    weatherTags: ["hot", "normal"],
    energyTags: ["normal", "high"],
    companionTags: ["solo", "friends"],
    active: true,
    craving: false,
    isSample: true,
    choiceCount: 0,
    preferenceDelta: 0,
    createdAt,
    updatedAt: createdAt,
  },
];
